import 'dart:convert';
import 'package:flutter/material.dart';
import 'services/action_guard.dart';
import 'services/admin_repository_extensions.dart';
import 'services/game_repository.dart';

class AdminConsolePage extends StatefulWidget {
  final String gameId;
  final GameRepository repository;
  final ActionGuard guard;
  final Future<void> Function() onChanged;
  const AdminConsolePage({super.key, required this.gameId, required this.repository, required this.guard, required this.onChanged});
  @override State<AdminConsolePage> createState() => _AdminConsolePageState();
}

class _AdminConsolePageState extends State<AdminConsolePage> {
  Map<String,dynamic> data={}; bool loading=true; String? error; int tab=0;
  @override void initState(){super.initState();load();}
  Future<void> load() async { if(mounted)setState((){loading=true;error=null;}); try{final r=await widget.repository.fetchAdminGameData(widget.gameId);if(mounted)setState((){data=r;loading=false;});}catch(e){if(mounted)setState((){error='$e';loading=false;});} }
  List<Map<String,dynamic>> rows(String k)=>((data[k] as List?)??const[]).map((e)=>Map<String,dynamic>.from(e as Map)).toList();
  Map<String,dynamic> get game=>Map<String,dynamic>.from((data['game'] as Map?)??const{});
  @override Widget build(BuildContext context){
    if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));
    if(error!=null)return Scaffold(appBar:AppBar(title:const Text('Admin Console')),body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text(error!,textAlign:TextAlign.center),const SizedBox(height:12),FilledButton(onPressed:load,child:const Text('Retry'))])));
    final pages=[_overview(),_players(),_countries(),_buildings(),_settings(),_marketplace()];
    return Scaffold(appBar:AppBar(title:Text('Admin Console • ${game['name']??''}'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[
      NavigationDestination(icon:Icon(Icons.dashboard),label:'Overview'),NavigationDestination(icon:Icon(Icons.people),label:'Players'),NavigationDestination(icon:Icon(Icons.public),label:'Countries'),NavigationDestination(icon:Icon(Icons.apartment),label:'Buildings'),NavigationDestination(icon:Icon(Icons.tune),label:'Settings'),NavigationDestination(icon:Icon(Icons.storefront),label:'Market') ]));
  }
  Widget _overview(){final ps=rows('players'),cs=rows('countries'),bs=rows('country_buildings'),ws=rows('wallets');return ListView(padding:const EdgeInsets.all(20),children:[Card(child:ListTile(leading:const Icon(Icons.admin_panel_settings),title:Text('${game['name']??'Game'} administration'),subtitle:Text('State: ${game['state']??''} • Tick ${game['current_tick']??0}'))),const SizedBox(height:12),LayoutBuilder(builder:(_,c)=>GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:c.maxWidth>=900?4:c.maxWidth>=600?2:1,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:2.5,children:[_stat('Players',ps.length,Icons.people),_stat('Countries',cs.length,Icons.public),_stat('Buildings',bs.length,Icons.apartment),_stat('Wallets',ws.length,Icons.account_balance_wallet)])),const SizedBox(height:16),_section('Game lifecycle',[_action('Ready',Icons.check_circle_outline,()=>widget.repository.setGameReady(widget.gameId)),_action('Start',Icons.play_arrow,()=>widget.repository.startGame(widget.gameId)),_action('Pause',Icons.pause,()=>widget.repository.pauseGame(widget.gameId)),_action('Resume',Icons.play_circle,()=>widget.repository.resumeGame(widget.gameId)),_action('Manual tick',Icons.timelapse,()=>widget.repository.advanceTick(widget.gameId)),_action('Finish',Icons.flag,()=>widget.repository.finishGame(widget.gameId))])]);}
  Widget _players(){final ps=rows('players'),ws=rows('wallets');return _page('Players',[for(final p in ps)Card(child:ListTile(leading:CircleAvatar(child:Text(_initial(p['display_name']))),title:Text('${p['display_name']??'Unnamed'}${p['is_admin']==true?' • ADMIN':''}'),subtitle:Text('Balance: ${_wallet(ws,p['id'])} USD\n${p['id']}'),isThreeLine:true,trailing:Wrap(children:[IconButton(onPressed:()=>_editPlayer(p),icon:const Icon(Icons.edit)),IconButton(onPressed:()=>_balance(p),icon:const Icon(Icons.account_balance_wallet))])),if(ps.isEmpty)const Card(child:ListTile(title:Text('No players.')))]);}
  Widget _countries(){final cs=rows('countries'),ps=rows('players');return _page('Countries',[Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:_createCountry,icon:const Icon(Icons.add),label:const Text('Add country'))),for(final c in cs)Card(child:ListTile(leading:const Icon(Icons.flag),title:Text('${c['name']} ${c['code']==null?'':'(${c['code']})'}'),subtitle:Text('Population: ${c['population']??0}\nOwner: ${_name(ps,c['owner_player_id'])}\nValue: ${_countryValue(c)} cents'),isThreeLine:true,trailing:IconButton(onPressed:()=>_editCountry(c,ps),icon:const Icon(Icons.edit)))),if(cs.isEmpty)const Card(child:ListTile(title:Text('No countries yet. Add the first country.'))) ]);}
  Widget _buildings(){final types=rows('building_types'),installed=rows('country_buildings'),countries=rows('countries');return _page('Buildings',[
    Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:_createBuildingType,icon:const Icon(Icons.add_business),label:const Text('Add building type'))),
    Card(child:ExpansionTile(title:Text('Building catalog (${types.length})'),children:[for(final b in types)ListTile(title:Text('${b['name']} (#${b['id']})'),subtitle:Text('Cost ${b['base_cost']} • Income ${b['base_income']} • Maintenance ${b['maintenance_cost']} • Max ${b['max_level']}'),trailing:IconButton(onPressed:()=>_editBuildingType(b),icon:const Icon(Icons.edit)))])),
    Align(alignment:Alignment.centerRight,child:FilledButton.icon(onPressed:types.isEmpty||countries.isEmpty?null:()=>_installBuilding(types,countries),icon:const Icon(Icons.add),label:const Text('Install building on country'))),
    Card(child:ExpansionTile(title:Text('Installed buildings (${installed.length})'),children:[for(final b in installed)ListTile(title:Text(_buildingName(b,types)),subtitle:Text('${_country(countries,b['country_id'])} • Level ${b['level']} • Count ${b['count']}'),trailing:IconButton(onPressed:()=>_editInstalled(b,types),icon:const Icon(Icons.edit)))])),
  ]);}
  Widget _settings()=>_page('Game settings',[Card(child:ListTile(title:const Text('Edit simulation settings'),subtitle:const Text('Name, slug, tick interval, current tick and starting balance'),trailing:FilledButton(onPressed:_editGame,child:const Text('Edit')))),for(final e in {'Name':game['name'],'Slug':game['slug'],'State':game['state'],'Current tick':game['current_tick'],'Tick interval':'${game['tick_interval_seconds']??0} seconds','Starting balance':'${game['config'] is Map?(game['config']['starting_balance']??0):0} cents','Started':game['started_at'],'Paused':game['paused_at'],'Finished':game['finished_at'],'Last tick':game['last_tick_at']}.entries)Card(child:ListTile(title:Text(e.key),trailing:Text('${e.value??'—'}')))]);
  Widget _marketplace(){final ls=rows('listings'),bs=rows('bids'),cs=rows('countries'),ps=rows('players');return _page('Marketplace',[Card(child:ExpansionTile(title:Text('Listings (${ls.length})'),children:[for(final l in ls)ListTile(title:Text('${_country(cs,l['country_id'])} • ${l['price']} ${l['currency']}'),subtitle:Text('${_name(ps,l['seller_player_id'])} • ${l['status']}'),trailing:IconButton(onPressed:()=>_editListing(l),icon:const Icon(Icons.edit)))])),Card(child:ExpansionTile(title:Text('Bids (${bs.length})'),children:[for(final b in bs)ListTile(title:Text('${b['amount']} ${b['currency']}'),subtitle:Text('${_name(ps,b['bidder_player_id'])} • ${b['status']}'),trailing:IconButton(onPressed:()=>_editBid(b),icon:const Icon(Icons.edit)))]))]);}
  Widget _page(String title,List<Widget> children)=>ListView(padding:const EdgeInsets.all(20),children:[Text(title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),...children]);
  Widget _stat(String l,int v,IconData i)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Icon(i),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l),Text('$v',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18))]))])));
  Widget _section(String t,List<Widget> c)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),...c])));
  Widget _action(String l,IconData i,Future<dynamic> Function() a)=>ListTile(leading:Icon(i),title:Text(l),trailing:FilledButton(onPressed:()=>_run(l,a),child:const Text('Run')));
  Future<void> _createCountry()async{final n=TextEditingController(),c=TextEditingController(),p=TextEditingController(text:'0');final ok=await _form('Add country',[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:c,decoration:const InputDecoration(labelText:'Code')), _num(p,'Population')]);if(ok!=true){n.dispose();c.dispose();p.dispose();return;}final name=n.text.trim();final code=c.text.trim();final pop=int.tryParse(p.text)??0;n.dispose();c.dispose();p.dispose();await _run('Create country',()=>widget.repository.adminCreateCountry(gameId:widget.gameId,name:name,code:code.isEmpty?null:code,population:pop));}
  Future<void> _createBuildingType()async{final n=TextEditingController(),s=TextEditingController(),cost=TextEditingController(text:'0'),income=TextEditingController(text:'0'),maint=TextEditingController(text:'0'),max=TextEditingController(text:'1');final ok=await _form('Add building type',[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:s,decoration:const InputDecoration(labelText:'Slug')), _num(cost,'Base cost'),_num(income,'Income per tick'),_num(maint,'Maintenance per tick'),_num(max,'Max level')]);if(ok!=true){for(final x in[n,s,cost,income,maint,max])x.dispose();return;}final a=n.text.trim(),b=s.text.trim(),v=int.tryParse(cost.text)??0,i=int.tryParse(income.text)??0,m=int.tryParse(maint.text)??0,l=int.tryParse(max.text)??1;for(final x in[n,s,cost,income,maint,max])x.dispose();await _run('Create building type',()=>widget.repository.adminCreateBuildingType(slug:b,name:a,baseCost:v,baseIncome:i,maintenanceCost:m,maxLevel:l).then((_){}));}
  Future<void> _installBuilding(List<Map<String,dynamic>> types,List<Map<String,dynamic>> countries)async{String? country=countries.first['id']?.toString();int? type=int.tryParse('${types.first['id']}');final level=TextEditingController(text:'1'),count=TextEditingController(text:'1');final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(_,set)=>AlertDialog(title:const Text('Install building'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:country,items:[for(final c in countries)DropdownMenuItem(value:'${c['id']}',child:Text('${c['name']}'))],onChanged:(v)=>set(()=>country=v)),DropdownButtonFormField<int>(initialValue:type,items:[for(final b in types)DropdownMenuItem(value:int.tryParse('${b['id']}'),child:Text('${b['name']}'))],onChanged:(v)=>set(()=>type=v)),_num(level,'Level'),_num(count,'Count')]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Install'))])));if(ok==true&&country!=null&&type!=null)await _run('Install building',()=>widget.repository.adminInstallBuilding(countryId:country!,buildingTypeId:type!,level:int.tryParse(level.text)??1,count:int.tryParse(count.text)??1));level.dispose();count.dispose();}
  Future<void> _editPlayer(Map<String,dynamic> p)async{final n=TextEditingController(text:'${p['display_name']??''}'),a=TextEditingController(text:'${p['avatar_url']??''}');var admin=p['is_admin']==true;final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(_,set)=>AlertDialog(title:const Text('Edit player'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Display name')),TextField(controller:a,decoration:const InputDecoration(labelText:'Avatar URL')),SwitchListTile(title:const Text('Admin'),value:admin,onChanged:(v)=>set(()=>admin=v))]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Save'))])));if(ok!=true){n.dispose();a.dispose();return;}final patch={'display_name':n.text.trim(),'avatar_url':a.text.trim(),'is_admin':admin};n.dispose();a.dispose();await _run('Update player',()=>widget.repository.adminUpdateEntity(entity:'players',id:'${p['id']}',patch:patch));}
  Future<void> _balance(Map<String,dynamic> p)async{final a=TextEditingController(),r=TextEditingController(text:'Admin adjustment');final ok=await _form('Balance: ${p['display_name']??'player'}',[TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount',helperText:'Negative removes balance')),TextField(controller:r,decoration:const InputDecoration(labelText:'Reason'))]);if(ok!=true){a.dispose();r.dispose();return;}final v=int.tryParse(a.text.trim());final why=r.text.trim();a.dispose();r.dispose();if(v==null||v==0)return;await _run('Adjust balance',()=>widget.repository.adminAdjustBalance(playerId:'${p['id']}',amount:v,reason:why.isEmpty?'Admin adjustment':why));}
  Future<void> _editCountry(Map<String,dynamic> c,List<Map<String,dynamic>> players)async{final n=TextEditingController(text:'${c['name']??''}'),code=TextEditingController(text:'${c['code']??''}'),pop=TextEditingController(text:'${c['population']??0}'),res=TextEditingController(text:jsonEncode(c['resources']??{}));String? owner=c['owner_player_id']?.toString();final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(_,set)=>AlertDialog(title:Text('Edit ${c['name']}'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:code,decoration:const InputDecoration(labelText:'Code')), _num(pop,'Population'),TextField(controller:res,maxLines:3,decoration:const InputDecoration(labelText:'Resources JSON')),DropdownButtonFormField<String?>(initialValue:owner,decoration:const InputDecoration(labelText:'Owner'),items:[const DropdownMenuItem<String?>(value:null,child:Text('Unowned')),...players.map((p)=>DropdownMenuItem<String?>(value:'${p['id']}',child:Text('${p['display_name']??'Player'}')))],onChanged:(v)=>set(()=>owner=v))])),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Save'))])));if(ok!=true){for(final x in[n,code,pop,res])x.dispose();return;}Map<String,dynamic> resources={};try{final decoded=jsonDecode(res.text);if(decoded is Map)resources=Map<String,dynamic>.from(decoded);}catch(_){if(mounted)_snack('Resources must be valid JSON');for(final x in[n,code,pop,res])x.dispose();return;}final patch={'name':n.text.trim(),'code':code.text.trim(),'population':int.tryParse(pop.text)??0,'resources':resources,'owner_player_id':owner};for(final x in[n,code,pop,res])x.dispose();await _run('Update country',()=>widget.repository.adminUpdateEntity(entity:'countries',id:'${c['id']}',patch:patch));}
  Future<void> _editBuildingType(Map<String,dynamic> b)async{final n=TextEditingController(text:'${b['name']}'),s=TextEditingController(text:'${b['slug']}'),cost=TextEditingController(text:'${b['base_cost']??0}'),income=TextEditingController(text:'${b['base_income']??0}'),maint=TextEditingController(text:'${b['maintenance_cost']??0}'),max=TextEditingController(text:'${b['max_level']??1}');final ok=await _form('Edit building type',[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:s,decoration:const InputDecoration(labelText:'Slug')),_num(cost,'Base cost'),_num(income,'Income per tick'),_num(maint,'Maintenance per tick'),_num(max,'Max level')]);if(ok!=true){for(final x in[n,s,cost,income,maint,max])x.dispose();return;}final patch={'name':n.text.trim(),'slug':s.text.trim(),'base_cost':int.tryParse(cost.text)??0,'base_income':int.tryParse(income.text)??0,'maintenance_cost':int.tryParse(maint.text)??0,'max_level':int.tryParse(max.text)??1};for(final x in[n,s,cost,income,maint,max])x.dispose();await _run('Update building type',()=>widget.repository.adminUpdateEntity(entity:'building_types',id:'${b['id']}',patch:patch));}
  Future<void> _editInstalled(Map<String,dynamic> b,List<Map<String,dynamic>> types)async{final level=TextEditingController(text:'${b['level']??1}'),count=TextEditingController(text:'${b['count']??1}');int? type=int.tryParse('${b['building_type_id']}');final ok=await _form('Edit installed building',[DropdownButtonFormField<int>(initialValue:type,decoration:const InputDecoration(labelText:'Building type'),items:[for(final t in types)DropdownMenuItem(value:int.tryParse('${t['id']}'),child:Text('${t['name']}'))],onChanged:(v){type=v;}),_num(level,'Level'),_num(count,'Count')]);if(ok!=true||type==null){level.dispose();count.dispose();return;}final patch={'building_type_id':type,'level':int.tryParse(level.text)??1,'count':int.tryParse(count.text)??1};level.dispose();count.dispose();await _run('Update installed building',()=>widget.repository.adminUpdateEntity(entity:'country_buildings',id:'${b['id']}',patch:patch));}
  Future<void> _editGame()async{final n=TextEditingController(text:'${game['name']??''}'),s=TextEditingController(text:'${game['slug']??''}'),interval=TextEditingController(text:'${game['tick_interval_seconds']??3600}'),tick=TextEditingController(text:'${game['current_tick']??0}'),starting=TextEditingController(text:'${game['config'] is Map?(game['config']['starting_balance']??100000):100000}');final ok=await _form('Edit game settings',[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:s,decoration:const InputDecoration(labelText:'Slug')),_num(interval,'Tick interval seconds'),_num(tick,'Current tick'),_num(starting,'Starting balance (cents)')]);if(ok!=true){for(final x in[n,s,interval,tick,starting])x.dispose();return;}final cfg=Map<String,dynamic>.from((game['config'] as Map?)??{});cfg['starting_balance']=int.tryParse(starting.text)??100000;final patch={'name':n.text.trim(),'slug':s.text.trim(),'tick_interval_seconds':int.tryParse(interval.text)??3600,'current_tick':int.tryParse(tick.text)??0,'config':cfg};for(final x in[n,s,interval,tick,starting])x.dispose();await _run('Update game settings',()=>widget.repository.adminUpdateGame(widget.gameId,patch));}
  Future<void> _editListing(Map<String,dynamic> l)async{final p=TextEditingController(text:'${l['price']??0}'),s=TextEditingController(text:'${l['status']??'open'}');final ok=await _form('Edit listing',[_num(p,'Price'),TextField(controller:s,decoration:const InputDecoration(labelText:'Status'))]);if(ok!=true){p.dispose();s.dispose();return;}final patch={'price':int.tryParse(p.text)??1,'status':s.text.trim()};p.dispose();s.dispose();await _run('Update listing',()=>widget.repository.adminUpdateEntity(entity:'country_listings',id:'${l['id']}',patch:patch));}
  Future<void> _editBid(Map<String,dynamic> b)async{final a=TextEditingController(text:'${b['amount']??0}'),s=TextEditingController(text:'${b['status']??'pending'}');final ok=await _form('Edit bid',[_num(a,'Amount'),TextField(controller:s,decoration:const InputDecoration(labelText:'Status'))]);if(ok!=true){a.dispose();s.dispose();return;}final patch={'amount':int.tryParse(a.text)??1,'status':s.text.trim()};a.dispose();s.dispose();await _run('Update bid',()=>widget.repository.adminUpdateEntity(entity:'bids',id:'${b['id']}',patch:patch));}
  Future<bool?> _form(String title,List<Widget> fields)=>showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text(title),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:fields)),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('Save'))]));
  Widget _num(TextEditingController c,String label)=>TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:label));
  Future<void> _run(String label,Future<dynamic> Function() action)async{try{await widget.guard.run('admin:${widget.gameId}:$label',action);await load();await widget.onChanged();if(mounted)_snack('$label completed.');}catch(e){if(mounted)_snack('$label failed: $e');}}
  void _snack(String t)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(t)));
  String _initial(dynamic v){final s='${v??'P'}'.trim();return s.isEmpty?'P':s.substring(0,1).toUpperCase();}
  String _name(List<Map<String,dynamic>> ps,dynamic id)=>ps.where((p)=>'${p['id']}'=='$id').firstOrNull?['display_name']?.toString()??'Unowned';
  String _country(List<Map<String,dynamic>> cs,dynamic id)=>cs.where((c)=>'${c['id']}'=='$id').firstOrNull?['name']?.toString()??'Country';
  String _buildingName(Map<String,dynamic> b,List<Map<String,dynamic>> ts)=>ts.where((t)=>'${t['id']}'=='${b['building_type_id']}').firstOrNull?['name']?.toString()??'Building';
  dynamic _wallet(List<Map<String,dynamic>> ws,dynamic id)=>ws.where((w)=>'${w['player_id']}'=='$id'&&w['currency']=='USD').firstOrNull?['balance']??0;
  int _countryValue(Map<String,dynamic> c){final p=c['population'];return p is num?p.toInt()*100:0;}
}
