name: world_trading_game
description: Flutter client for World Trading Game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  interactive_world_map: ^0.1.3

flutter:
  uses-material-design: true
